project: default
source:
  repoURL: https://github.com/devcrypted/demo-helm
  path: .
  targetRevision: HEAD
  helm:
    valueFiles:
      - prod-values.yaml
destination:
  server: https://kubernetes.default.svc
  namespace: prod
syncPolicy:
  automated:
    prune: true
    selfHeal: true
  syncOptions:
    - CreateNamespace=true
